// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE3YmLZa13ouYYTGYJVqgvCugEQpGRnVw',
    appId: '1:1069071256417:web:b1c2d596d46d8959351320',
    messagingSenderId: '1069071256417',
    projectId: 'swapn-slimai',
    authDomain: 'swapn-slimai.firebaseapp.com',
    storageBucket: 'swapn-slimai.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvGIeEIFulm5oSScyzJ4VsQ99ucXtoddc',
    appId: '1:1069071256417:android:d15dc5b42b8fde07351320',
    messagingSenderId: '1069071256417',
    projectId: 'swapn-slimai',
    storageBucket: 'swapn-slimai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh5lip145L9jmN-sw2WLb73td0BlIDLdk',
    appId: '1:1069071256417:ios:9f5df19f5604c3e4351320',
    messagingSenderId: '1069071256417',
    projectId: 'swapn-slimai',
    storageBucket: 'swapn-slimai.appspot.com',
    iosClientId: '1069071256417-qihh4h18l5dte8vv8g209bavva8g0uv4.apps.googleusercontent.com',
    iosBundleId: 'com.example.swapn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh5lip145L9jmN-sw2WLb73td0BlIDLdk',
    appId: '1:1069071256417:ios:9f5df19f5604c3e4351320',
    messagingSenderId: '1069071256417',
    projectId: 'swapn-slimai',
    storageBucket: 'swapn-slimai.appspot.com',
    iosClientId: '1069071256417-qihh4h18l5dte8vv8g209bavva8g0uv4.apps.googleusercontent.com',
    iosBundleId: 'com.example.swapn',
  );
}
