name: swapn
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.3.0
  image_picker: ^0.8.6
  firebase_auth: ^4.1.4
  http: ^0.13.5
  async: ^2.9.0
  path: ^1.8.2
  cupertino_icons: ^1.0.2

  
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo-beyolix.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/preview.png
    - assets/images/health.png
    - assets/images/medical.jpg
    - assets/images/defaultimage.png
    - assets/images/loading.gif
    - assets/images/cartoon-sad.png
    - assets/images/beyolix-app.png
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
